name: XJCraftPlot
version: 1.0.0
main: org.xjcraft.plot.PlotPlugin
authors: 
  - Cat73
  - Nami
depends: 
  - Bukkit-Boot
commands:
  plotplugin:
    usage: /<command> help
permissions:
  plot.admin:
    default: op
