name: XJCraftPlot
version: 1.0.0
main: org.xjcraft.plot.XJPlot
authors: 
  - Cat73
  - Nami
depends: 
  - Bukkit-Boot
commands:
  xjplot:
    usage: /<command> help
permissions:
  xjplot.admin:
    default: op
